export const GOOGLE_CAREER_FORM_URL =
  "https://forms.google.com"; // replace with your real Google Form / Google Doc link

export const SERVICE_CATEGORIES = [
  "Hair",
  "Face",
  "Makeup",
  "Nails",
  "Spa",
  "Bridal",
];

export const SAMPLE_SERVICES = [
  {
    id: 1,
    name: "Hair Spa",
    category: "Hair",
    description: "Deep nourishment and smooth finish for damaged hair.",
    price: 999,
    duration: 45,
    image: "/images/service1.jpg",
  },
  {
    id: 2,
    name: "Hair Cut & Styling",
    category: "Hair",
    description: "Precision cut with premium styling finish.",
    price: 699,
    duration: 40,
    image: "/images/service2.jpg",
  },
  {
    id: 3,
    name: "Luxury Facial",
    category: "Face",
    description: "Glow-enhancing facial treatment with hydration boost.",
    price: 1499,
    duration: 60,
    image: "/images/service3.jpg",
  },
  {
    id: 4,
    name: "Cleanup",
    category: "Face",
    description: "Quick freshening treatment for regular maintenance.",
    price: 799,
    duration: 30,
    image: "/images/service4.jpg",
  },
  {
    id: 5,
    name: "Party Makeup",
    category: "Makeup",
    description: "Elegant makeup look for parties and special events.",
    price: 2499,
    duration: 75,
    image: "/images/service5.jpg",
  },
  {
    id: 6,
    name: "Bridal Makeup",
    category: "Bridal",
    description: "Premium bridal makeover package with luxury finish.",
    price: 8999,
    duration: 180,
    image: "/images/service6.jpg",
  },
  {
    id: 7,
    name: "Manicure",
    category: "Nails",
    description: "Clean, shape, massage and polish for beautiful hands.",
    price: 599,
    duration: 35,
    image: "/images/service7.jpg",
  },
  {
    id: 8,
    name: "Pedicure",
    category: "Nails",
    description: "Foot care and polish with relaxing treatment.",
    price: 699,
    duration: 40,
    image: "/images/service8.jpg",
  },
  {
    id: 9,
    name: "Relaxing Spa",
    category: "Spa",
    description: "Relaxing body care session to de-stress and refresh.",
    price: 1999,
    duration: 70,
    image: "/images/service9.jpg",
  },
];